openapi: 3.0.1
info:
  title: user-api
  description: API Definition of user-api
  version: 1.0.0
servers:
- url: http://localhost:8290/user
paths:
  /add:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /list:
    get:
      responses:
        default:
          description: Default response
  /sellers:
    get:
      responses:
        default:
          description: Default response
  /admins:
    get:
      responses:
        default:
          description: Default response
